[package]
name = "vortex"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = {version="1", features = ["derive"]}
serde_json = "1"

[dependencies.uuid]
version = "1.20.0"
features = [
    "v4",
]